### ISSUE TITLE
establish project website

### ISSUE THREAD

**Issue by onthebreeze** [uncefact/project-crm#1]
Using github pages over this repository (so website url will be uncefact.github.io/project-crm ) please implement a landing page and documentation site

 - following this design template https://projects.invisionapp.com/share/JS139VVCC68K#/screens 
 - leveraging the same technology and tooling approach as already used by https://github.com/uncefact/vckit

The outcome should be the project website is accessible and is linked to

 - this github repository - https://github.com/uncefact/project-crm
 - the relevant slack channel - https://uncefact.slack.com/archives/C05AV647QKC
 - maintainable docs - very similar to the vckit example (eg https://uncefact.github.io/vckit/docs/overview/introduction)

**Comment by kshychko** [comment]
@onthebreeze, the website has been deployed to https://uncefact.github.io/project-crm/

**Comment by onthebreeze** [comment]
done - see https://uncefact.github.io/project-crm/
